
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
  mongo-seed:
    container_name: testeContratos-mongo-seed
    image: mongo:latest
    volumes:
      - /mnt/c/Users/pedro/OneDrive/Ambiente de Trabalho/3ano/2sem/ENGWEB2024-Normal/ENGWEB2024-Normal/contratos2024.json:/datasets//mnt/c/Users/pedro/OneDrive/Ambiente de Trabalho/3ano/2sem/ENGWEB2024-Normal/ENGWEB2024-Normal/contratos2024.json

    command: /bin/bash -c "mongoimport --host mongodb -d contratos -c contratos --type json --file /datasets//mnt/c/Users/pedro/OneDrive/Ambiente de Trabalho/3ano/2sem/ENGWEB2024-Normal/ENGWEB2024-Normal/contratos2024.json --jsonArray"
